@GameStore_HostAddress = http://localhost:5242

### Add a new game
POST http://localhost:5242/api/games/add
Content-Type: application/json

{
  "title": "DiRT Rally 2.0",
  "description": "DiRT Rally 2.0 dares you to carve your way through a selection of iconic rally locations from across the globe, in the most powerful off-road vehicles ever made, knowing that the smallest mistake could end your stage.",
  "imageUrl": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/690790/header.jpg?t=1730918452",
  "videoUrl": "https://video.fastly.steamstatic.com/store_trailers/256969266/movie480_vp9.webm?t=1694601905",
  "releaseDate": "2019-02-26",
  "publisher": "Codemasters",
  "price": 7.99,
  "genre": "Racing"
}

### Get all games
GET http://localhost:5242/api/games
Content-Type: application/json

### Add a new user
POST http://localhost:5242/api/auth/register
Content-Type: application/json

{
  "username": "zara",
  "email": "zara.sivova@gmail.com",
  "firstName": "Zara",
  "lastName": "Sivova",
  "age": 23,
  "password": "Zara@1234",
  "confirmPassword": "Zara@1234"
}

### Login user
POST http://localhost:5242/api/auth/login
Content-Type: application/json
{
    "username": "hristo",
    "password": "admiN@123"
}